-- Intentionally a no-op.
--
-- As originally generated, every statement in this migration duplicated one already applied by an
-- earlier migration:
--   * CREATE TABLE "merchant_price_adjustment_policies"  -> 0044_powerful_thena
--   * CREATE TABLE "calendar_reschedule_proposals"       -> 0045_wonderful_boomerang
--   * CREATE TABLE "calendar_reschedule_trusted_rules"   -> 0045_wonderful_boomerang
--   * ALTER "schedule_conflicts" ADD "occurrence_date"   -> 0046_schedule_conflicts_occurrence_date
--
-- It was produced by `drizzle-kit generate` run against a database that had none of 0044-0046 applied,
-- so the generator re-emitted all three. Unlike hand-written 0046 (which used ADD COLUMN IF NOT EXISTS),
-- the generated statements were unguarded, so `pnpm db:migrate` failed with
-- `relation "merchant_price_adjustment_policies" already exists` on any clean database and rolled the
-- whole transaction back, leaving zero tables. Found on a from-scratch Windows setup.
--
-- Emptied rather than deleted on purpose: drizzle-kit chains its meta/*_snapshot.json files by prevId,
-- so removing this migration's journal entry and snapshot would break that chain for 0048 onward and
-- with it any future `drizzle-kit generate`. Keeping the entry with no SQL preserves the lineage and is
-- harmless to re-run on databases that already applied the original.
SELECT 1;
