import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { users } from "./identity";

/**
 * PRIV-002 — "make user ownership operational, not merely a policy statement." One row per requested
 * export; the actual file is a JSON manifest in S3 (never a permanent public URL — see StorageService),
 * generated by a background worker job since a user's full data graph can be large enough to be worth
 * not blocking the HTTP request that requested it.
 */
export const exportJobs = pgTable("export_jobs", {
  id: text("id").primaryKey(),
  ownerUserId: text("owner_user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  state: text("state").notNull().default("queued"), // "queued" | "processing" | "completed" | "failed"
  storageKey: text("storage_key"),
  errorMessage: text("error_message"),
  requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
});
