import { pgTable, text, timestamp, integer, jsonb } from "drizzle-orm/pg-core";
import { users } from "./identity";
import { encryptedText } from "./encrypted-type";

/**
 * PRIV-002 — "make user ownership operational, not merely a policy statement." One row per requested
 * export; the actual file is a JSON manifest in S3 (never a permanent public URL — see StorageService),
 * generated by a background worker job since a user's full data graph can be large enough to be worth
 * not blocking the HTTP request that requested it.
 */
export const exportJobs = pgTable("export_jobs", {
  id: text("id").primaryKey(),
  ownerUserId: text("owner_user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  state: text("state").notNull().default("queued"), // "queued" | "processing" | "completed" | "failed"
  storageKey: text("storage_key"),
  // §28 encryption-inventory sweep — same class of column as its already-encrypted siblings
  // (extractionRuns.errorDetail, syncRuns.errorDetail, connections.healthDetail): a background job's own
  // failure message can echo details from the user's own data graph (e.g. a row it choked on).
  errorMessage: encryptedText("error_message"),
  // PRIV-002 "category selection" — null means "export everything," preserving every export requested
  // before this column existed (and the default when a caller doesn't pass any) exactly as-is. A non-null
  // array scopes DataExportService.buildManifest to only those top-level domains (see its own doc comment
  // for the recognized keys).
  selectedCategories: jsonb("selected_categories").$type<string[] | null>(),
  // PRIV-002 "size/progress" — populated by the worker once the manifest is actually built (see
  // worker-main.ts's dataExportWorker), never estimated up front: this app has no cheap way to know either
  // number before doing the real query/serialize work, so both stay null while `state` is "queued"/
  // "processing" and the UI shows the state badge alone until they're set.
  itemCount: integer("item_count"),
  estimatedSizeBytes: integer("estimated_size_bytes"),
  requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
});
